[mypy]
python_version = {{python_version}}
strict = True
warn_unused_ignores = True
warn_return_any = True
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-tests.*]
disallow_untyped_defs = False
